---

name: CapesLocker
version: 2.0.0
main: unarray\capeslocker\capeslocker
src-namespace-prefix: unarray\capeslocker
api: 4.0.0
extensions: [gd]

author: Unarray
description: Add your own capes to the server !
website: https://github.com/Unarray

# - - - - - - - - - - - - - - - -

permissions:

  capeslocker.command.capes:
    description: "Allow the player to run \"capes\" command"
    default: true

  capeslocker.command.managecapes:
    description: "Allow the player to run \"managecapes\" command"
    default: op

  capeslocker.command.playerscapescleaner:
    description: "Allow the player to run \"playerscapescleaner\" command"
    default: op
...